---
title: "Epigenomics"
author: "S. Quiñones, J. Rojas, X. Díaz"
date: "3/24/2022"
output: 
  html_document:
    toc: yes
  pdf_document:
    toc: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Introduction
  Our assay is to compare enrichment of H3K4me3 in promoter regions with HiC fragments, which most likely will represent enhancers, from B cells.
  


# Analysis
##Data Description
-Species: Homo Sapiens
-Cell type: B cell
-Subject: 27 year old female


## Defining a histone of interest

  To perform our analyisis, it is important to select carefully a target histone. In this case, we have chosen H3K4me3. The biological reason for doing so is that H3K4me3 has been reported associated to increased promoter activity and transcription. Therefore, whilst performing our analysis, we expect this histone to have an increased activity in promoters respective to enhancers.

## ¿Is there Histone enrichment comparing enhancers and fragments?
### Statistical proof

## ¿What transcription factor is enriched in both promoters and enhancers?

## Using non redundant Jaspar colection

## Using permutations as control sequences

## Conclusion

# Sources